<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // === BANNER (Trang chủ) ===
            [
                'key' => 'banner_image',
                'value' => '/images/banner.png',
                'type' => 'image',
                'group' => 'banner',
                'label' => 'Ảnh Banner',
                'sort_order' => 1,
            ],
            [
                'key' => 'banner_title',
                'value' => 'MẶC ĐÚNG GU<br>COOL ĐÚNG CHẤT',
                'type' => 'text',
                'group' => 'banner',
                'label' => 'Tiêu đề Banner',
                'sort_order' => 2,
            ],
            [
                'key' => 'banner_subtitle',
                'value' => 'Đồng hành cùng đàn ông việt trên hành trình xây dựng phong thái tự tin và chinh phục mục tiêu',
                'type' => 'textarea',
                'group' => 'banner',
                'label' => 'Mô tả Banner',
                'sort_order' => 3,
            ],
            [
                'key' => 'banner_btn1_text',
                'value' => 'Khám Phá Sản Phẩm',
                'type' => 'text',
                'group' => 'banner',
                'label' => 'Nút 1 - Text',
                'sort_order' => 4,
            ],
            [
                'key' => 'banner_btn1_link',
                'value' => '/san-pham',
                'type' => 'text',
                'group' => 'banner',
                'label' => 'Nút 1 - Link',
                'sort_order' => 5,
            ],
            [
                'key' => 'banner_btn2_text',
                'value' => 'Liên Hệ Hợp Tác',
                'type' => 'text',
                'group' => 'banner',
                'label' => 'Nút 2 - Text',
                'sort_order' => 6,
            ],
            [
                'key' => 'banner_btn2_link',
                'value' => '/hop-tac',
                'type' => 'text',
                'group' => 'banner',
                'label' => 'Nút 2 - Link',
                'sort_order' => 7,
            ],

            // === VỀ BIVINTO (Trang chủ) ===
            [
                'key' => 'about_title',
                'value' => 'VỀ BIVINTO',
                'type' => 'text',
                'group' => 'about',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'about_subtitle',
                'value' => 'Bivinto - Nơi Mọi Hành Trình Mạnh Mẽ Bắt Đầu',
                'type' => 'text',
                'group' => 'about',
                'label' => 'Phụ đề',
                'sort_order' => 2,
            ],
            [
                'key' => 'about_description',
                'value' => 'Bivinto được sinh ra từ khát vọng giúp đàn ông Việt dễ dàng tiếp cận thời trang chất lượng, xây dựng phong thái tự tin và trưởng thành hơn mỗi ngày.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Mô tả',
                'sort_order' => 3,
            ],
            [
                'key' => 'about_image_1',
                'value' => '/images/pic1.png',
                'type' => 'image',
                'group' => 'about',
                'label' => 'Ảnh Về Bivinto 1',
                'sort_order' => 4,
            ],
            [
                'key' => 'about_image_2',
                'value' => '/images/pic2.png',
                'type' => 'image',
                'group' => 'about',
                'label' => 'Ảnh Về Bivinto 2',
                'sort_order' => 5,
            ],

            // === LĨNH VỰC HOẠT ĐỘNG (Trang chủ) ===
            [
                'key' => 'business_title',
                'value' => 'LĨNH VỰC HOẠT ĐỘNG',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'business_subtitle',
                'value' => 'Bivinto Đồng Hành Cùng Đối Tác Và Khách Hàng',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Phụ đề',
                'sort_order' => 2,
            ],
            [
                'key' => 'business_card1_image',
                'value' => '/images/pic3.png',
                'type' => 'image',
                'group' => 'business',
                'label' => 'Ảnh - Gia Công',
                'sort_order' => 3,
            ],
            [
                'key' => 'business_card1_title',
                'value' => 'GIA CÔNG THỜI TRANG',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Tiêu đề - Gia Công',
                'sort_order' => 4,
            ],
            [
                'key' => 'business_card1_desc',
                'value' => 'Thiết kế, sản xuất, OEM/ ODM',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Mô tả - Gia Công',
                'sort_order' => 5,
            ],
            [
                'key' => 'business_card2_image',
                'value' => '/images/pic4.png',
                'type' => 'image',
                'group' => 'business',
                'label' => 'Ảnh - Nhập Sỉ',
                'sort_order' => 6,
            ],
            [
                'key' => 'business_card2_title',
                'value' => 'NHẬP SỈ',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Tiêu đề - Nhập Sỉ',
                'sort_order' => 7,
            ],
            [
                'key' => 'business_card2_desc',
                'value' => 'Chính sách hấp dẫn, nguồn hàng ổn định',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Mô tả - Nhập Sỉ',
                'sort_order' => 8,
            ],
            [
                'key' => 'business_card3_image',
                'value' => '/images/pic5.png',
                'type' => 'image',
                'group' => 'business',
                'label' => 'Ảnh - Bán Lẻ',
                'sort_order' => 9,
            ],
            [
                'key' => 'business_card3_title',
                'value' => 'BÁN LẺ',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Tiêu đề - Bán Lẻ',
                'sort_order' => 10,
            ],
            [
                'key' => 'business_card3_desc',
                'value' => 'Thời trang hiện đại, chất lượng cao',
                'type' => 'text',
                'group' => 'business',
                'label' => 'Mô tả - Bán Lẻ',
                'sort_order' => 11,
            ],

            // === FOOTER ===
            [
                'key' => 'footer_address',
                'value' => 'Số 82 Phố Dịch Vọng Hậu, Phường Cầu Giấy, Thành Phố Hà Nội, Việt Nam',
                'type' => 'textarea',
                'group' => 'footer',
                'label' => 'Địa chỉ',
                'sort_order' => 1,
            ],
            [
                'key' => 'footer_phone',
                'value' => '+84 345 677 395',
                'type' => 'text',
                'group' => 'footer',
                'label' => 'Số điện thoại',
                'sort_order' => 2,
            ],
            [
                'key' => 'footer_email',
                'value' => 'bivinto@gmail.com',
                'type' => 'text',
                'group' => 'footer',
                'label' => 'Email',
                'sort_order' => 3,
            ],
            [
                'key' => 'footer_facebook',
                'value' => '#',
                'type' => 'text',
                'group' => 'footer',
                'label' => 'Link Facebook',
                'sort_order' => 4,
            ],
            [
                'key' => 'footer_zalo',
                'value' => '#',
                'type' => 'text',
                'group' => 'footer',
                'label' => 'Link Zalo',
                'sort_order' => 5,
            ],
            [
                'key' => 'footer_tiktok',
                'value' => '#',
                'type' => 'text',
                'group' => 'footer',
                'label' => 'Link Tiktok',
                'sort_order' => 6,
            ],
            [
                'key' => 'footer_shopee',
                'value' => '#',
                'type' => 'text',
                'group' => 'footer',
                'label' => 'Link Shopee',
                'sort_order' => 7,
            ],

            // === TRANG VỀ BIVINTO - HERO ===
            [
                'key' => 'aboutpage_hero_title',
                'value' => 'HÀNH TRÌNH XÂY DỰNG<br>PHONG THÁI ĐÀN ÔNG VIỆT',
                'type' => 'text',
                'group' => 'aboutpage_hero',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'aboutpage_hero_image',
                'value' => '/images/banner-aboutus.png',
                'type' => 'image',
                'group' => 'aboutpage_hero',
                'label' => 'Ảnh Banner',
                'sort_order' => 2,
            ],

            // === TRANG VỀ BIVINTO - CÂU CHUYỆN ===
            [
                'key' => 'aboutpage_story_title',
                'value' => 'BIVINTO',
                'type' => 'text',
                'group' => 'aboutpage_story',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'aboutpage_story_subtitle',
                'value' => '"Nơi Mọi Hành Trình Mạnh Mẽ Bắt Đầu"',
                'type' => 'text',
                'group' => 'aboutpage_story',
                'label' => 'Phụ đề',
                'sort_order' => 2,
            ],
            [
                'key' => 'aboutpage_story_intro_left',
                'value' => 'Bivinto không bắt đầu từ những trung tâm thời trang sôi động hay những cơ hội sẵn có.',
                'type' => 'textarea',
                'group' => 'aboutpage_story',
                'label' => 'Giới thiệu ngắn (trái)',
                'sort_order' => 3,
            ],
            [
                'key' => 'aboutpage_story_intro_right',
                'value' => 'Thương hiệu được hình thành từ một khát vọng rất giản đơn: "Giúp đàn ông Việt dễ dàng tiếp cận thời trang phù hợp với phong thái và sự tự tin hơn trên hành trình chinh phục mục tiêu".',
                'type' => 'textarea',
                'group' => 'aboutpage_story',
                'label' => 'Giới thiệu ngắn (phải)',
                'sort_order' => 4,
            ],
            [
                'key' => 'aboutpage_story_image1',
                'value' => '/images/about1.png',
                'type' => 'image',
                'group' => 'aboutpage_story',
                'label' => 'Ảnh câu chuyện 1',
                'sort_order' => 5,
            ],
            [
                'key' => 'aboutpage_story_content1',
                'value' => '<p class="about-desc mb-3 mb-md-4">Bivinto được khởi nguồn từ một tỉnh miền núi, nơi cơ hội tiếp cận với thời trang và phong cách sống hiện đại còn nhiều hạn chế.</p><p class="about-desc mb-3 mb-md-4">Trong khi nhiều người có điều kiện để lựa chọn và xây dựng hình ảnh cá nhân, rất nhiều đàn ông trẻ lại gặp khó khăn trong việc tìm kiếm những trang phục phù hợp với vóc dáng, môi trường làm việc và phong cách sống của mình.</p><p class="about-desc m-0">Từ chính những trải nghiệm đó, một câu hỏi luôn xuất hiện: <strong>"Điều gì đang ngăn cản đàn ông Việt thể hiện khí chất thật sự của họ?"</strong>. Câu hỏi ấy đã trở thành động lực cho sự ra đời của Bivinto.</p>',
                'type' => 'textarea',
                'group' => 'aboutpage_story',
                'label' => 'Nội dung câu chuyện 1',
                'sort_order' => 6,
            ],
            [
                'key' => 'aboutpage_story_image2',
                'value' => '/images/about2.png',
                'type' => 'image',
                'group' => 'aboutpage_story',
                'label' => 'Ảnh câu chuyện 2',
                'sort_order' => 7,
            ],
            [
                'key' => 'aboutpage_story_content2',
                'value' => '<p class="about-desc mb-3 mb-md-4">Hành trình xây dựng Bivinto không bắt đầu bằng những điều thuận lợi.</p><p class="about-desc mb-3 mb-md-4">Từ việc nghiên cứu sản phẩm, tìm kiếm đối tác sản xuất, kiểm soát chất lượng, xây dựng đội ngũ cho đến phát triển thương hiệu, mọi bước đi đều là những thử thách mới. Nhưng cũng giống như hành trình trưởng thành của mỗi người đàn ông, chính những khó khăn ấy đã tạo nên bản lĩnh và sự kiên định.</p><p class="about-desc m-0">Bivinto tin rằng: <strong>"Điều tạo nên sự khác biệt không phải những gì ta đang có, mà là những gì ta dám theo đuổi"</strong>. Đó cũng là tinh thần mà thương hiệu muốn truyền tải đến khách hàng thông qua từng sản phẩm và trải nghiệm.</p>',
                'type' => 'textarea',
                'group' => 'aboutpage_story',
                'label' => 'Nội dung câu chuyện 2',
                'sort_order' => 8,
            ],

            // === TRANG VỀ BIVINTO - Ý NGHĨA THƯƠNG HIỆU ===
            [
                'key' => 'aboutpage_meaning_title',
                'value' => 'Ý NGHĨA<br>THƯƠNG HIỆU',
                'type' => 'text',
                'group' => 'aboutpage_meaning',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'aboutpage_meaning_subtitle',
                'value' => 'BIVINTO – TRỞ THÀNH NGƯỜI CHINH PHỤC',
                'type' => 'text',
                'group' => 'aboutpage_meaning',
                'label' => 'Phụ đề',
                'sort_order' => 2,
            ],
            [
                'key' => 'aboutpage_meaning_content',
                'value' => '<p class="meaning-text mb-4">Tên gọi Bivinto được tạo nên từ 3 yếu tố:</p><ul class="list-unstyled meaning-list mb-4"><li><strong>Be</strong> - Đại diện cho sự trưởng thành và hành trình trở thành phiên bản tốt hơn của chính mình.</li><li><strong>Vincere</strong> - Trong tiếng Latin mang ý nghĩa "chinh phục", tượng trưng cho bản lĩnh, ý chí và khát vọng tiến lên.</li><li><strong>To</strong> - Thể hiện sự hướng tới mục tiêu, tinh thần chủ động và không ngừng phát triển.</li></ul><p class="meaning-text m-0">Kết hợp lại, Bivinto mang ý nghĩa: Trở thành người chinh phục – Hướng tới thành công.</p>',
                'type' => 'textarea',
                'group' => 'aboutpage_meaning',
                'label' => 'Nội dung',
                'sort_order' => 3,
            ],

            // === TRANG VỀ BIVINTO - CHÚNG TÔI TIN RẰNG ===
            [
                'key' => 'aboutpage_belief_title',
                'value' => 'CHÚNG TÔI TIN RẰNG',
                'type' => 'text',
                'group' => 'aboutpage_belief',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'aboutpage_belief1_title',
                'value' => 'THỜI TRANG<br>KHÔNG CHỈ LÀ QUẦN ÁO',
                'type' => 'text',
                'group' => 'aboutpage_belief',
                'label' => 'Tiêu đề mục 1',
                'sort_order' => 2,
            ],
            [
                'key' => 'aboutpage_belief1_desc',
                'value' => 'Đó là cách một người đàn ông thể hiện sự tôn trọng với chính mình và những người xung quanh.',
                'type' => 'textarea',
                'group' => 'aboutpage_belief',
                'label' => 'Mô tả mục 1',
                'sort_order' => 3,
            ],
            [
                'key' => 'aboutpage_belief2_title',
                'value' => 'SỰ TỰ TIN BẮT ĐẦU<br>TỪ SỰ PHÙ HỢP',
                'type' => 'text',
                'group' => 'aboutpage_belief',
                'label' => 'Tiêu đề mục 2',
                'sort_order' => 4,
            ],
            [
                'key' => 'aboutpage_belief2_desc',
                'value' => 'Một bộ trang phục đúng gu, vừa vặn và chỉn chu có thể thay đổi cách một người xuất hiện mỗi ngày.',
                'type' => 'textarea',
                'group' => 'aboutpage_belief',
                'label' => 'Mô tả mục 2',
                'sort_order' => 5,
            ],
            [
                'key' => 'aboutpage_belief3_title',
                'value' => 'ĐƠN GIẢN<br>NHƯNG KHÁC BIỆT',
                'type' => 'text',
                'group' => 'aboutpage_belief',
                'label' => 'Tiêu đề mục 3',
                'sort_order' => 6,
            ],
            [
                'key' => 'aboutpage_belief3_desc',
                'value' => 'Bivinto không chạy theo xu hướng nhất thời. Chúng tôi tập trung vào những giá trị bền vững, tính ứng dụng cao và sự tinh tế trong từng chi tiết.',
                'type' => 'textarea',
                'group' => 'aboutpage_belief',
                'label' => 'Mô tả mục 3',
                'sort_order' => 7,
            ],

            // === TRANG HỢP TÁC - BANNER ===
            [
                'key' => 'collab_title',
                'value' => 'HỢP TÁC',
                'type' => 'text',
                'group' => 'collab_banner',
                'label' => 'Tiêu đề trang',
                'sort_order' => 1,
            ],
            [
                'key' => 'collab_banner_image',
                'value' => '/images/banner-cooperate.png',
                'type' => 'image',
                'group' => 'collab_banner',
                'label' => 'Ảnh Banner',
                'sort_order' => 2,
            ],

            // === TRANG HỢP TÁC - GIA CÔNG ===
            [
                'key' => 'collab_section1_title',
                'value' => 'LIÊN HỆ GIA CÔNG',
                'type' => 'text',
                'group' => 'collab_giacong',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'collab_section1_image',
                'value' => '/images/about1.png',
                'type' => 'image',
                'group' => 'collab_giacong',
                'label' => 'Ảnh minh họa',
                'sort_order' => 2,
            ],
            [
                'key' => 'collab_section1_content',
                'value' => '<p>Bivinto được khơi nguồn từ một thời đại mới, nơi cơ thể tiếp cận với thời trang và phong cách sống hiện đại của nhiều bạn trẻ.</p><p>Trang phục của người có điều kiện dễ lựa chọn và xây dựng hình ảnh cá nhân, rất nhiều đàn ông trở lại gặp khó khăn trong việc tìm kiếm những trang phục phù hợp với vóc dáng, môi trường làm việc và phong cách sống của mình.</p><p>Từ chính những trải nghiệm đó, một câu hỏi luôn xuất hiện: <strong>"Điều gì đáng quan tâm thay việc thể hiện khí chất thật sự của họ?"</strong>. Câu hỏi ấy đã trở thành động lực cho sự ra đời của Bivinto.</p>',
                'type' => 'textarea',
                'group' => 'collab_giacong',
                'label' => 'Nội dung',
                'sort_order' => 3,
            ],

            // === TRANG HỢP TÁC - NHẬP SỈ ===
            [
                'key' => 'collab_section2_title',
                'value' => 'LIÊN HỆ NHẬP SỈ',
                'type' => 'text',
                'group' => 'collab_nhapsi',
                'label' => 'Tiêu đề',
                'sort_order' => 1,
            ],
            [
                'key' => 'collab_section2_image',
                'value' => '/images/about2.png',
                'type' => 'image',
                'group' => 'collab_nhapsi',
                'label' => 'Ảnh minh họa',
                'sort_order' => 2,
            ],
            [
                'key' => 'collab_section2_content',
                'value' => '<p>Hành trình xây dựng Bivinto không bắt đầu bằng những điều vĩ đại.</p><p>Từ việc nghiên cứu sản phẩm, tìm kiếm đối tác sản xuất, kiểm soát chất lượng, cho tới việc xây dựng những chiến dịch truyền thông, mọi bước đi đều là những thử thách lớn. Nhưng cũng giống như hành trình trưởng thành của mỗi người đàn ông, chính những khó khăn ấy đã tạo nên bản lĩnh và sự kiên định.</p><p>Bivinto tin rằng: <strong>"Điều tạo nên sự khác biệt không phải những gì ta đang có, mà là những gì ta làm thế nào"</strong>. Đó cũng là tâm thư mà thương hiệu muốn chuyển tải đến khách hàng thông qua từng sản phẩm và trải nghiệm.</p>',
                'type' => 'textarea',
                'group' => 'collab_nhapsi',
                'label' => 'Nội dung',
                'sort_order' => 3,
            ],

            // === TRANG HỢP TÁC - LIÊN HỆ ===
            [
                'key' => 'collab_contact_title',
                'value' => 'Liên Hệ Với Chúng Tôi',
                'type' => 'text',
                'group' => 'collab_contact',
                'label' => 'Tiêu đề form',
                'sort_order' => 1,
            ],
            [
                'key' => 'collab_contact_subtitle',
                'value' => 'Quý khách hàng vui lòng điền đầy đủ thông tin để đội ngũ Bivinto tư vấn',
                'type' => 'textarea',
                'group' => 'collab_contact',
                'label' => 'Phụ đề form',
                'sort_order' => 2,
            ],

            // === TRANG CHÍNH SÁCH ===
            [
                'key' => 'policy_title',
                'value' => 'CHÍNH SÁCH',
                'type' => 'text',
                'group' => 'policy_general',
                'label' => 'Tiêu đề trang',
                'sort_order' => 1,
            ],
            [
                'key' => 'policy1_title',
                'value' => 'Chính Sách Thành Viên',
                'type' => 'text',
                'group' => 'policy_items',
                'label' => 'Tiêu đề mục 1',
                'sort_order' => 1,
            ],
            [
                'key' => 'policy1_content',
                'value' => '<ul class="policy-list"><li>Quyền lợi và chiết khấu dành cho thành viên Bivinto.</li><li>Điều kiện để nâng hạng thành viên và duy trì thứ hạng.</li><li>Các chương trình khuyến mãi đặc quyền trong các dịp Lễ, Tết, Sinh nhật.</li><li>Quy định về việc sử dụng điểm tích lũy khi mua sắm trực tiếp hoặc online.</li></ul>',
                'type' => 'textarea',
                'group' => 'policy_items',
                'label' => 'Nội dung mục 1',
                'sort_order' => 2,
            ],
            [
                'key' => 'policy2_title',
                'value' => 'Chính Sách Giao Hàng',
                'type' => 'text',
                'group' => 'policy_items',
                'label' => 'Tiêu đề mục 2',
                'sort_order' => 3,
            ],
            [
                'key' => 'policy2_content',
                'value' => '<ul class="policy-list"><li>Nhận ship COD toàn quốc, thanh toán khi nhận hàng.</li><li>Đơn nội thành nhận trong ngày, với đơn ngoại thành nhận hàng sau 1-2 ngày. Những đơn hàng đi tỉnh tùy thuộc vào vị trí địa lý và hay gặp mà thời gian giao hàng có thể dao động từ 3-5 ngày.</li><li>Liên hệ hotline: <strong>+84 345 677 395</strong> để biết thông tin nhanh nhất về đơn hàng.</li><li>Miễn phí vận chuyển cho đơn hàng trên 1 triệu.</li><li>Hỗ trợ phí vận chuyển cho đơn hàng trên 500k (tối đa 30k) - Không áp dụng đối với sản phẩm sale.</li></ul>',
                'type' => 'textarea',
                'group' => 'policy_items',
                'label' => 'Nội dung mục 2',
                'sort_order' => 4,
            ],
            [
                'key' => 'policy3_title',
                'value' => 'Quy Định Đổi Trả',
                'type' => 'text',
                'group' => 'policy_items',
                'label' => 'Tiêu đề mục 3',
                'sort_order' => 5,
            ],
            [
                'key' => 'policy3_content',
                'value' => '<ul class="policy-list"><li>Hỗ trợ đổi size/sản phẩm trong vòng 7 ngày kể từ ngày nhận hàng.</li><li>Sản phẩm đổi trả phải còn nguyên tem mác, chưa qua sử dụng và chưa giặt ủi.</li><li>Không áp dụng đổi trả với các sản phẩm trong chương trình khuyến mãi (Sale).</li><li>Khách hàng vui lòng chịu phí ship 2 chiều nếu đổi trả không do lỗi từ nhà sản xuất.</li></ul>',
                'type' => 'textarea',
                'group' => 'policy_items',
                'label' => 'Nội dung mục 3',
                'sort_order' => 6,
            ],
            [
                'key' => 'policy4_title',
                'value' => 'Chính Sách Xử Lý Khiếu Nại',
                'type' => 'text',
                'group' => 'policy_items',
                'label' => 'Tiêu đề mục 4',
                'sort_order' => 7,
            ],
            [
                'key' => 'policy4_content',
                'value' => '<ul class="policy-list"><li>Bivinto cam kết giải quyết mọi khiếu nại của khách hàng trong vòng 24 - 48 giờ làm việc.</li><li>Trường hợp sản phẩm bị lỗi do nhà sản xuất (rách, bẩn, lỗi đường may), Bivinto sẽ chịu 100% phí đổi trả.</li><li>Trường hợp giao sai mẫu/sai size, chúng tôi sẽ tiến hành đổi sản phẩm đúng yêu cầu nhanh nhất có thể.</li><li>Mọi thắc mắc và khiếu nại vui lòng liên hệ hotline hoặc gửi tin nhắn trực tiếp qua Fanpage.</li></ul>',
                'type' => 'textarea',
                'group' => 'policy_items',
                'label' => 'Nội dung mục 4',
                'sort_order' => 8,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}